### ISSUE TITLE
Production readiness / upstreaming with SQLite?

### ISSUE THREAD

**Issue by ghost** [benwebber/sqlite3-uuid#3]
Hello,

This looks great, and like it should be a standard feature (or extension) of SQLite.

Just wondering -- is this production ready? Have you considered discussing with the sqlite authors about upstreaming this?

Cheers,

**Comment by benwebber** [comment]
Thanks!

I have given some thought to submitting this upstream as a loadable extension. I'd say the code is solid, but there's a few things that stand in the way of merging it:

* I don't have a Windows machine to test against.
* I'd need to rewrite the tests in TCL to fit with the rest of the SQLite suite.
* I'm not certain the project would accept code that depends on libcrypto and libuuid.

That being said, it's definitely worth asking!

**Comment by ghost** [comment]
Howdy,

Any update on this? I'm fine with some workarounds, but maybe the authors would have something to say.

If you'd prefer that I'd chime in, I'm happy to contact them -- maybe linking them to this issue is sufficient as a start?

Cheers,

**Comment by benwebber** [comment]
Thanks for keeping on this @rbastic. I will reach out to the mailing list this weekend.

**Comment by benwebber** [comment]
There was no interest on the sqlite-users mailing list:

https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg112786.html

That's alright. I'll work on some documentation for building a custom version of SQLite with this extension.
